### Minecraft服务器登录请求
POST http://localhost:25580/login
Content-Type: application/json

{
  "username": "1652039138@qq.com",
  "password": "112859Sunny"
}

###

### Yggdrasil认证服务器验证请求
POST https://skin.nyauru.cn/api/yggdrasil/authserver/authenticate
Content-Type: application/json

{
  "agent": {
    "name": "Minecraft",
    "version": "1.20.1"
  },
  "username": "1652039138@qq.com",
  "password": "112859Sunny",
  "requestUser": false
}

###

### 带clientToken的认证请求
POST https://skin.nyauru.cn/api/yggdrasil/authserver/authenticate
Content-Type: application/json

{
  "agent": {
    "name": "Minecraft",
    "version": "1.20.1"
  },
  "username": "1652039138@qq.com",
  "password": "112859Sunny",
  "clientToken": "",
  "requestUser": false
}

###
